時計を改良
deBroglieeeen/atd-app pull request #17
Opened 2023-02-13 06:11 UTC by riko-okubo

### 【問題点】
時計が毎秒更新されるたびにレンダリングしていた。

### 【解決法】
新たなコンポーネントで時計を実装し、TopPage.tsxで表示だけするようにする。

### 【結果】
<img width="184" alt="image" src="https://user-images.githubusercontent.com/81846197/218383624-ca03c67d-8f05-4fee-90cd-36562f95c02d.png">
無限にレンダリングしていたのが、有限になった。
<img width="701" alt="スクリーンショット 2023-02-13 15 06 07" src="https://user-images.githubusercontent.com/81846197/218383212-962e101a-a073-49b6-a019-7915313d57f6.png">

### 【課題】
有限とはいえど、10回くらい読み込んでいる。これの原因を調べる。

2023-02-14 10:53 UTC, tomoyuki-hiranuma requested changes
知らない間にだいぶ書けるようになってる！！

変数名、ファイル名、ファイル分割周りは僕含めてまだ課題感あるから一緒に向上していきましょ 👍 

ちょっとだけ指摘

2023-02-14 10:53 UTC, tomoyuki-hiranuma commented on src/components/Clock/Time.tsx
> +import { useEffect, useState } from "react";
このファイルはカスタムフックだと思うんですけど、カスタムフックはカスタムフックってわかるようにしましょう！
https://ja.reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook

2023-02-14 10:53 UTC, tomoyuki-hiranuma commented on src/components/TopPage.tsx
> +  console.log("!");
不要なconsole.logは削除

2023-02-14 13:08 UTC, tomoyuki-hiranuma commented on src/components/Clock/useTime.tsx
> +import { useEffect, useState } from "react";
useTimer.tsxにして、timeをcurrentTimeにした方が意味が通るような気がしてるんだけど、どう思う？？

2023-02-14 13:12 UTC, tomoyuki-hiranuma commented on src/components/Clock/useTime.tsx
> +  const [time, updateTime] = useState(Date.now());
[hoge, setHoge] = useState(initialData);
の方がreact感出ると思う

なんでsetHogeっていう名前がいいのかどこかにあった気がしたけど見当たらない、、

2023-02-14 13:37 UTC, tomoyuki-hiranuma commented on src/components/Clock/useTime.tsx
> +  const [time, updateTime] = useState(Date.now());
https://ja.reactjs.org/docs/faq-state.html#when-is-setstate-asynchronous
https://github.com/facebook/react/blob/main/packages/react/src/ReactHooks.js#L99
https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactInternalTypes.js#L370
https://ja.reactjs.org/docs/reconciliation.html
useStateはコンポーネントのレンダリングを最適化するために非同期にバッチ処理的にまとめてステートを更新する。それを明示的に示すために[hoge, setHoge]の命名にするのがよいかも(そんな感じの記事をどこかで見たことあって、ふと思った)

2023-02-14 13:59 UTC, riko-okubo commented on src/components/Clock/useTime.tsx
> +import { useEffect, useState } from "react";
const [currentTime, useCurrentTime] = useState(Date.now());
という解釈であっていますか？

2023-02-25 06:02 UTC, tomoyuki-hiranuma approved these changes
いくつかコメントあるけど、全体的にはLGTM

2023-02-25 06:02 UTC, tomoyuki-hiranuma commented on src/components/TopPage.tsx
>    const [nowTime, setNowtime] = useState(now);
nowTime使ってなさそう、、、？？

2023-02-28 05:43 UTC, riko-okubo reviewed
## useTimerで打刻時の時刻を取得する
時計を改良した時に作ったカスタムフックのuseTimerを使って、打刻時刻を取得するようにした。
　　→表示している時刻とボタンを押した時刻のずれがなくなった。

## ハッシュマップを使って勤怠状況を表示し、状況に合わせて色も変化する。
* 勤怠状況（勤務中、勤務外、休憩中）をハッシュマップを使って表示するようにした。
　　→Hasuraのdefault（"勤務外"）を修正しなくてはならない。
* 勤怠状況の表示を、chakra ui のextendThemeを使って状況に応じて色が変わるようにした。

2023-03-31 05:24 UTC, merged